### ISSUE TITLE
User agents with () break

### ISSUE THREAD

**Issue by masylum** [gildas-lormeau/single-file-cli#88] opened 2024-05-23 21:10 UTC
Due to how the args are parsed and sent to chromium, options can't contain parenthesis.

Repro case:

```
single-file https://google.com --user-agent="Mozilla/5.0 () Firefox"
```

but this does not fail:

```
single-file https://google.com --user-agent="Mozilla/5.0 Firefox"
```

While debugging, if I evaluate `this.options.args` in deno-polyfill, we are sending this to chromium:

```
'--user-agent=Mozilla/5.0 () Firefox'
```

**Comment by gildas-lormeau** [comment] 2024-05-27 13:40
How would you describe the problem on your side? On my machine (macOS), the command `single-file https://example.com --user-agent="Mozilla/5.0 () Firefox" --browser-debug` works as expected and I can see in the debugger that the user-agent value is correct in the HTTP headers, see the screenshot below.

<img width="1277" alt="image" src="https://github.com/gildas-lormeau/single-file-cli/assets/396787/8b5d6f44-45f7-43e3-b6df-05ac95a5b6cd">

**Comment by gildas-lormeau** [comment] 2024-08-06 14:11
I'm closing the issue because I was not able to reproduce it. Feel free to comment it though.

**Closed by gildas-lormeau** 2024-08-06 14:11 UTC
